### ISSUE TITLE
Missing a way to configure other type of keyboard

### ISSUE THREAD

**Issue by bgiegel** [micmonay/keybd_event#8]
Thanx for this library !

I just wanted to mention that it would be useful to add support for azerty, dvorak and other types of keyboards.

**Comment by micmonay** [comment]
Hi

I don't find a solution for the moment, but my skill is not sufficient for this issue, because on Windows, Linux and Mac OS the solutions are different. On windows the Keycode is virtual and the keyboard seems correct for the master keys, but on Linux and Mac, the Keycode seems to be material.
(If my analysis is correct)
